### ISSUE TITLE
crypto_sign_keypair bug

### ISSUE THREAD

**Issue by b354c502** [devi/Salt#2]
https://github.com/devi/Salt/blob/master/Salt.php: the function crypto_sign_keypair() has several issues. When a seed is provided, it's length is checked using "$sk !==" when in fact it should be "$sk->count() !==". Also, the seed is supposed to be 32 bytes, but you compare it to Salt::sign_PRIVATEKEY, which is 64 bytes, causing an exception whenever a deterministic seed is provided. The seed only becomes 64 bytes after being hashed (ie, $azDigest).

**Comment by devi** [comment]
Thanks for spotting this :+1:
